### ISSUE TITLE
Npm deploy does not work

### ISSUE THREAD

**Issue by mkiael** [TransNeptunianStudios/Triangulum-III#15]

**Comment by Reicher** [comment]
Something something input was not found

**Comment by andersrydman** [comment]
funkar `npm run dev` eller uppstår samma fel där?
Om ni tagit hem senaste sedan vi lagt till @orange-games/phaser-input-node modulen så kan ni behöva köra `npm install` för att den modulen ska hamna i ./node_modules', vilket är vart webpack letar efter den.

**Comment by Reicher** [comment]
run dev funkar bra. Men för npm run deploy får jag nada. Även om jag kört npm install innan. Borde inte "run dev" fungera dåligt om man inte kört npm install med?

**Comment by andersrydman** [comment]
Felet var att jag missat att det var 2 olika config-filer bereonde på om webpack packade ihop koden för dev eller prod. La till script-loadern  under loaders i webpack.production.config.js och så nu borde det vara löst.

Glömde rebasea också, så det blev en ful commit. Men testa nu,  jag lyckas inte återskapa det lokalt längre.
